name: Shellcheck

on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Shellcheck
      run: apt-get install shellcheck
    - name: Run tests
      run: shellcheck script.bash
