name: Shellcheck

on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Shellcheck
      run: scversion="stable" && \
           wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && \
           cp "shellcheck-${scversion}/shellcheck" /usr/bin/ && \
           shellcheck --version
    - name: Run tests
      run: shellcheck script.bash
