name: Shellcheck

on: check_run

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Shellcheck
      run: sudo apt install shellcheck
    - name: Run Shellcheck
      run: shellcheck script.bash
